export const themes = {
	light: {
		'--color-background': '#ffffff',
		'--color-text': '#1a202c',
		'--color-primary': '#3182ce',
		'--color-secondary': '#e53e3e',
		'--color-accent': '#37cdbe',
		'--color-neutral': '#f3f4f6',
	},
	dark: {
		'--color-background': '#1a202c',
		'--color-text': '#e2e8f0',
		'--color-primary': '#63b3ed',
		'--color-secondary': '#d53f8c',
		'--color-accent': '#37cdbe',
		'--color-neutral': '#3d4451',
	},
	cyberpunk: {
		'--color-background': '#ffd700',
		'--color-text': '#ff00ff',
		'--color-primary': '#00ffff',
		'--color-secondary': '#ff4500',
		'--color-accent': '#ff0099',
		'--color-neutral': '#202020',
	},
	winter: {
		'--color-background': '#eff6ff',
		'--color-text': '#1e40af',
		'--color-primary': '#3b82f6',
		'--color-secondary': '#64748b',
		'--color-accent': '#93c5fd',
		'--color-neutral': '#e0f2fe',
	},
	cupcake: {
		'--color-background': '#faf7f5',
		'--color-text': '#291334',
		'--color-primary': '#65c3c8',
		'--color-secondary': '#ef9fbc',
		'--color-accent': '#eeaf3a',
		'--color-neutral': '#e5e6e4',
	},
	bumblebee: {
		'--color-background': '#ffffff',
		'--color-text': '#181830',
		'--color-primary': '#e0a82e',
		'--color-secondary': '#f9d72f',
		'--color-accent': '#37cdbe',
		'--color-neutral': '#f3f4f6',
	},
	emerald: {
		'--color-background': '#fafafa',
		'--color-text': '#134e4a',
		'--color-primary': '#10b981',
		'--color-secondary': '#1d4ed8',
		'--color-accent': '#9333ea',
		'--color-neutral': '#f3f4f6',
	},
	corporate: {
		'--color-background': '#ffffff',
		'--color-text': '#0a2b33',
		'--color-primary': '#0070f3',
		'--color-secondary': '#3d4451',
		'--color-accent': '#4caf50',
		'--color-neutral': '#f3f4f6',
	},
	synthwave: {
		'--color-background': '#2d1b69',
		'--color-text': '#e9eff6',
		'--color-primary': '#d926a9',
		'--color-secondary': '#ff5700',
		'--color-accent': '#37cdbe',
		'--color-neutral': '#202020',
	},
	retro: {
		'--color-background': '#efeae4',
		'--color-text': '#291334',
		'--color-primary': '#ef9fbc',
		'--color-secondary': '#b56576',
		'--color-accent': '#eec170',
		'--color-neutral': '#d5c3aa',
	},
	valentine: {
		'--color-background': '#fdf2f8',
		'--color-text': '#5a203c',
		'--color-primary': '#e91e63',
		'--color-secondary': '#ff80ab',
		'--color-accent': '#37cdbe',
		'--color-neutral': '#f3f4f6',
	},
	halloween: {
		'--color-background': '#212121',
		'--color-text': '#ff6f00',
		'--color-primary': '#ff8f00',
		'--color-secondary': '#37474f',
		'--color-accent': '#d84315',
		'--color-neutral': '#263238',
	},
	garden: {
		'--color-background': '#f8fafc',
		'--color-text': '#234e52',
		'--color-primary': '#059669',
		'--color-secondary': '#10b981',
		'--color-accent': '#6ee7b7',
		'--color-neutral': '#d1fae5',
	},
	forest: {
		'--color-background': '#1b4332',
		'--color-text': '#95d5b2',
		'--color-primary': '#52b788',
		'--color-secondary': '#40916c',
		'--color-accent': '#2d6a4f',
		'--color-neutral': '#d8f3dc',
	},
	aqua: {
		'--color-background': '#d0f4de',
		'--color-text': '#023e8a',
		'--color-primary': '#0077b6',
		'--color-secondary': '#0096c7',
		'--color-accent': '#00b4d8',
		'--color-neutral': '#caf0f8',
	},
	lofi: {
		'--color-background': '#262626',
		'--color-text': '#f3f4f6',
		'--color-primary': '#3d4451',
		'--color-secondary': '#5b626b',
		'--color-accent': '#73787c',
		'--color-neutral': '#1c1c1c',
	},
	pastel: {
		'--color-background': '#fdf2f8',
		'--color-text': '#3d4451',
		'--color-primary': '#a78bfa',
		'--color-secondary': '#ef4444',
		'--color-accent': '#37cdbe',
		'--color-neutral': '#e5e7eb',
	},
	black: {
		'--color-background': '#000000',
		'--color-text': '#ffffff',
		'--color-primary': '#3d4451',
		'--color-secondary': '#73787c',
		'--color-accent': '#5b626b',
		'--color-neutral': '#202020',
	},
	luxury: {
		'--color-background': '#1c1c1c',
		'--color-text': '#ffffff',
		'--color-primary': '#a3a3a3',
		'--color-secondary': '#73787c',
		'--color-accent': '#575c60',
		'--color-neutral': '#323639',
	},
	dracula: {
		'--color-background': '#282a36',
		'--color-text': '#f8f8f2',
		'--color-primary': '#ff79c6',
		'--color-secondary': '#8be9fd',
		'--color-accent': '#bd93f9',
		'--color-neutral': '#44475a',
	},
	autumn: {
		'--color-background': '#fffaf0',
		'--color-text': '#9c4221',
		'--color-primary': '#ed8936',
		'--color-secondary': '#c05621',
		'--color-accent': '#dd6b20',
		'--color-neutral': '#fbd38d',
	},
	acid: {
		'--color-background': '#f9fafb',
		'--color-text': '#111827',
		'--color-primary': '#f43f5e',
		'--color-secondary': '#ec4899',
		'--color-accent': '#e11d48',
		'--color-neutral': '#f9a8d4',
	},
	lemonade: {
		'--color-background': '#faf7e5',
		'--color-text': '#333d29',
		'--color-primary': '#f4b41a',
		'--color-secondary': '#ff9900',
		'--color-accent': '#ffbb00',
		'--color-neutral': '#ffcc33',
	},
	night: {
		'--color-background': '#1f2937',
		'--color-text': '#f9fafb',
		'--color-primary': '#1e40af',
		'--color-secondary': '#1d4ed8',
		'--color-accent': '#3b82f6',
		'--color-neutral': '#111827',
	},
	coffee: {
		'--color-background': '#261a15',
		'--color-text': '#d0a08c',
		'--color-primary': '#8d5524',
		'--color-secondary': '#b5651d',
		'--color-accent': '#c68642',
		'--color-neutral': '#a0522d',
	},
	spring: {
		'--color-background': '#e5ffed',
		'--color-text': '#134e4a',
		'--color-primary': '#10b981',
		'--color-secondary': '#047857',
		'--color-accent': '#6ee7b7',
		'--color-neutral': '#d1fae5',
	},
	summer: {
		'--color-background': '#fffbf0',
		'--color-text': '#92400e',
		'--color-primary': '#fbbf24',
		'--color-secondary': '#f59e0b',
		'--color-accent': '#fde68a',
		'--color-neutral': '#fef3c7',
	},
	accent: {
		'--color-background': '#f4f4f4',
		'--color-text': '#333333',
		'--color-primary': '#ffaa00',
		'--color-secondary': '#ff6600',
		'--color-accent': '#ffd700',
		'--color-neutral': '#ffeecc',
	},
};

export interface ThemeValue {
	'--color-background': string;
	'--color-text': string;
	'--color-primary': string;
	'--color-secondary': string;
	'--color-accent': string;
	'--color-neutral': string;
}

export type ThemeProperty = {
	[key: string]: ThemeValue;
};

export type Themas = keyof typeof themes